name: Deploy resources on dev environment

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        required: true
        default: dev
        options:
        - dev
        - prod

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: 1.21.0

      - name: Build Lambda Functions
        run: |
          make build-all
      - name: Upload artifact list-lambda
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: list-accounts-lambda
          path: infra/tf_generated_aws_list-lambda
      - name: Upload artifact verify-takeover
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: verify-takeover-lambda
          path: infra/tf_generated_aws_verify-takeover
      - name: Upload artifact azure lambda
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: azure-lambda
          path: infra/tf_generated_azure

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Set AWS region from environment
        id: set-region
        run: |
          if [ "${{ inputs.env }}" = "dev" ]; then
            echo "region=eu-south-1" >> $GITHUB_OUTPUT
            "role=${{ secrets.DEV_ARN_ROLE }}" >> $GITHUB_OUTPUT
          else
            echo "region=eu-west-1" >> $GITHUB_OUTPUT
            "role=${{ secrets.PROD_ARN_ROLE }}" >> $GITHUB_OUTPUT
          fi
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef
        with:
          role-to-assume: ${{ steps.set-region.outputs.role }}
          aws-region: ${{ steps.set-region.outputs.region }}
      - name: Download artifact list-accounts-lambda
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: list-accounts-lambda
          path: infra/tf_generated_aws_list-lambda
      - name: Download artifact verify-takeover-lambda
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: verify-takeover-lambda
          path: infra/tf_generated_aws_verify-takeover
      - name: Download artifact azure-lambda
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: azure-lambda
          path: infra/tf_generated_azure
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36
        with:
          terraform_version: '1.9.3'
      - name: Run terraform plan
        run: |
          cd infra
          ./terraform.sh plan ${{ inputs.env }}