name: Azure prod unhappy path check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 7 * * 2' #Every tuesday at 7:00 UTC 
jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-24.04
    environment: prod
    env:
      DEPLOY_ENV: prod
      LAMBDA: "azure-lambda"
    permissions:
      id-token: write   # This is required for requesting the OIDC JWT
      contents: read    # This is required for actions/checkout Action
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0
        with:
          aws-region: ${{ vars.REGION }}
          role-to-assume: ${{ secrets.ARN_ROLE }}
          role-session-name: oidc-gha-assume-role-session
      - name: Azure login using OIDC
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
      - name: Make scripts executable
        id: make-scripts-executable
        run: |
          chmod +x scripts/*/*.sh
      - name: Change slack channel to dev
        id: change-slack-channel-to-dev
        run: ./scripts/common/change_slack_channel.sh
        env: 
          ENV_VALUE: ${{ secrets.DEV_ENV_VALUE }}
      - name: Create Dangling Case
        id: generate-dangling-case
        run: ./scripts/azure/create_dangling_case.sh
      - name: Invoke lambda
        id: invoke-lambda-aws-subdomain-tool
        run: ./scripts/common/invoke_lambda.sh
      - name: Change slack channel to prod
        id: change-slack-channel-to-prod
        run: ./scripts/common/change_slack_channel.sh
        env: 
          ENV_VALUE: ${{ secrets.PROD_ENV_VALUE }}
      - name: Delete resources
        id: delete-dns-zone
        run: ./scripts/azure/reset.sh
      - name: Azure Logout
        id: az_logout
        if: always()
        shell: bash
        run: |
            az logout
            az cache purge
            az account clear